### ISSUE TITLE
Move docs to wiki

### ISSUE THREAD

**Issue by drGrove** [hashbang/os#12]
Our docs are already starting to blow up a bit and I think it might make more sense to move the large bulk of these documents into a wiki. This will allow us to provide more fine grained linking and a TOC.

**Comment by lrvick** [comment]
I don't want any github specific features as we will move off github when time permits.

Markdown in the repo and KISS for now is ideal. When we are ready I would support having those markdown docs auto-generated into a static site for #!os that also has links to latest releases etc.
