### ISSUE TITLE
Custom OTA server

### ISSUE THREAD

**Issue by ghost** [hashbang/os#19]
Are these the right steps for custom OTA server

Thank you!

**Comment by lrvick** [comment]
We are currently working on the OTA system and will have an automated path to do all of this soon. Leaving this open until then.

**Comment by drGrove** [comment]
The updater app we use relies heavily on ensuring that metadata is provided. So we'll either need to patch updater (which we're already working on in #9 for PGP Verification) to either not directly require this metadata or just implement the same strategy in our update server as exists [here](https://github.com/AndroidHardening/script/blob/pie/generate_metadata.py)

**Comment by respinout** [comment]
Thank you both for responses.

If I understood correctly the page source for Updater app should be like:

```
{
    "result": [{
        "channel": "STABLE",
        "filename": "marlin-ota_update-PQ2A.190205.003.2019.03.23.12.zip",
        "fingerprint": "Android/aosp_marlin/marlin:9/PQ2A.190205.003/2019.03.23.12:user/release-keys",
        "incremental": "PQ2A.190205.003.2019.03.23.12",
        "timestamp": "1553343204",
        "url": "https://www.domain.com/update/marlin-ota_update-PQ2A.190205.003.2019.03.23.12.zip"
    }]
}
```

Based on metadata generation script output on OTA zip file was:
2019.03.23.12 1553343204 PQ2A.190205.003

**Comment by lrvick** [comment]
We could do a dynamic patch like we do for fdroid. This would be easy. Marking as an easy first PR for someone.

**Comment by ypid** [comment]
> just implement the same strategy in our update server as exists [here](https://github.com/AndroidHardening/script/blob/pie/generate_metadata.py)

Thanks @drGrove for implementing it this way. Works nicely. This issue can be closed.

Ref: https://github.com/hashbang/aosp-build/pull/2
