### ISSUE TITLE
pull access denied for hashbang-os

### ISSUE THREAD

**Issue by sjdrc** [hashbang/os#21]
when running ```make DEVICE=taimen keys```
I get the output
```
mkdir -p build
Unable to find image 'hashbang-os:latest' locally
docker: Error response from daemon: pull access denied for hashbang-os, repository does not exist or may require 'docker login'.
See 'docker run --help'.
Makefile:36: recipe for target 'fetch' failed
make: *** [fetch] Error 125
```

The makefile is trying to pull the image hashbang-os instead of hashbang/os

**Comment by lrvick** [comment]
I don't think the makefile in master should have these issues now on a full clean start.

If you have further issues please feel free to re-open
