### ISSUE TITLE
Additional patches in central repository

### ISSUE THREAD

**Issue by ypid** [hashbang/os#24]
I would propose to have a common repository containing additional patches which can be included into a #!os build. https://github.com/RattlesnakeOS/community_patches seems like a good place. git submodule uses SHA1 commit hash references under the hood so when we include community_patches as ./patches/additional/ for example, it is still pinned. Then the patches could be enabled in `config.yml` individually. `config.yml` could then be published alongside to allow reproducibility and verification.

./patches/additional/ would contain additional hardening patches but which are optional (not required) for building AOSP.

00004-increase-default-maximum-password-length.patch should be enabled by default. I am not sure about the other once by default.

Also, I would propose to move ./patches/platform/add-backup.patch into community_patches because I find this very helpful and others could profit from this as well.

Maybe it would be easier to fork https://github.com/RattlesnakeOS/community_patches to https://github.com/hashbang/os-additional-patches and use that so that you have control over it. This would make handling easier. https://github.com/RattlesnakeOS/community_patches could still pull from it then.

**Comment by lrvick** [comment]
I have no problem merging useful patches for security/privacy directly into the patches directory or including them with --author. Trying to avoid the endless pile-of-repo-soup normally required to work on an android rom project. We will see how long that lasts...

I am also totally in favor adding config.yml support to pull in patches from external repos, even if #!os keeps its curated set of patches in tree.

 +1 for the idea, but it may take me a bit to implement it.

Feel free to beat me to it if you get cycles.

**Comment by lrvick** [comment]
I have now fully decoupled the main project into "aosp-build" and this repo now just contains patches and overlays that pertain to hashbang-specific customizations.

You could just as easily use submodules since you can use any paths you want in the config.yml now to include extra patches.

I hope this increases flexibility. Thoughts?

**Comment by ypid** [comment]
Nice work! This works for me, thanks for the configuration option. I am closing the issue as you already addressed the "central patch repository" question above.
