### ISSUE TITLE
factory images don't include boot/radio and other image types

### ISSUE THREAD

**Issue by lrvick** [hashbang/os#3]
Google Factory images contain:
* abl.img
* aop.img
* boot.img
* bootloader-crosshatch-b1c1-0.1-4948814.img
* cmnlib64.img
* cmnlib.img
* devcfg.img
* dtbo.img
* hyp.img
* keymaster.img
* modem.img
* product.img
* qupfw.img
* radio-crosshatch-g845-00023-180815-b-4956438.img
* system.img
* system_other.img
* tz.img
* vbmeta.img
* vendor.img
* xbl_config.img
* xbl.img

Many of these are currently unidentified. Some of them that are generated by the build system are not copied to factory images by ```device/common/generate-factory-images-common.sh```

In particular boot.img and radio.img are currently not in paths the script detects and don't make it into the build.

**Comment by lrvick** [comment]
@thestinger feel free to point me in the right direction here.

**Comment by thestinger** [comment]
android-prepare-vendor deals with all of this among other things.

**Comment by thestinger** [comment]
I contributed to making android-prepare-vendor work well, mostly with ideas and bug reports, and I'd highly recommend using that. Trying to use Google's incomplete / broken driver releases won't work well. It's better to use android-prepare-vendor to extract from the official factory images.

**Comment by lrvick** [comment]
android-prepare-vendor is now working as expected.
