### ISSUE TITLE
make error: permission denied

### ISSUE THREAD

**Issue by cmetzinnernet** [hashbang/os#4]
mkdir tmp
cd tmp
git clone https://github.com/hashbang/os.git
cd os
make DEVICE=crosshatch
Makefile:74: warning: overriding recipe for target 'clean'
Makefile:66: warning: ignoring old recipe for target 'clean'
Sending build context to Docker daemon  351.2kB
Step 1/11 : FROM ubuntu:bionic
 ---> 93fd78260bd1
Step 2/11 : MAINTAINER Hashbang Team <team@hashbang.sh>
 ---> Using cache
 ---> 7e974edc4d0e
Step 3/11 : ENV HOME=/home/build
 ---> Using cache
 ---> ced8215a73f6
Step 4/11 : ENV PATH=/home/build/out/host/linux-x86/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 ---> Using cache
 ---> a9c481f0c72d
Step 5/11 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 52ed31037040
Step 6/11 : RUN     useradd -G plugdev,sudo -ms /bin/bash build &&     apt-get update &&     apt-get install -y         repo         aapt         sudo         openjdk-8-jdk         android-tools-adb         bc         bsdmainutils         cgpt         bison         build-essential         curl         flex         git         g++-multilib        gcc-multilib        gnupg         gperf        imagemagick         lib32ncurses5-dev         lib32readline-dev         lib32z1-dev         liblz4-tool         libncurses5-dev         libsdl1.2-dev         libssl-dev         libwxgtk3.0-dev         libxml2         libxml2-utils         lzop         pngcrush         python3         python3-git         rsync         schedtool         squashfs-tools         xsltproc         yasm         zip         zlib1g-dev         wget     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*     && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
 ---> Using cache
 ---> f1a2abf53529
Step 7/11 : USER build
 ---> Using cache
 ---> 3e7dafffe81e
Step 8/11 : WORKDIR /home/build
 ---> Using cache
 ---> 27ad991d408d
Step 9/11 : ADD scripts/ /usr/local/bin/
 ---> 968fb1474159
Step 10/11 : ADD ./ /opt/android/
 ---> 32bcfb8534ab
Step 11/11 : CMD [ "/bin/bash", "/usr/local/bin/build.sh" ]
 ---> Running in e3c020c6f291
Removing intermediate container e3c020c6f291
 ---> 14ba658bfadf
Successfully built 14ba658bfadf
Successfully tagged hashbang/os:latest
standard_init_linux.go:190: exec user process caused "permission denied"
make: *** [Makefile:11: build] Error 1

Are there assumptions being made about the host OS's directory structure? (Anything special about /home/build?)

**Comment by RyanSquared** [comment]
> Are there assumptions being made about the host OS's directory structure?

That should be specific to the Docker container. It sets the `$HOME` variable for that build. It's weird that it gives that output, given it "seems" to work correctly. Do you (or @lrvick) know why `make` isn't printing out the commands run? That seems rather odd, and doesn't help with debugging.

**Comment by lrvick** [comment]
I made a number of fixes. Try again?

**Comment by lrvick** [comment]
make now outputs commands. Made piles of build fixes and can get bootable/usable builds on my device.

Closing this until I hear otherwise.
