### ISSUE TITLE
Customize this android rom with a specific feature, is it possible ?

### ISSUE THREAD

**Issue by KabDeveloper** [hashbang/os#42]
Hi,

I need to customize this Android ROM so it can have a specific requirement before installation !

As an example, when someone Flash the Android ROM into the phone, he will be asked to enter a password and to confirm it, then 10 PIN will be given for him and be written into a paper so if someday he forgot the password, he can recover it by using this PINs just like Google do it for Gmail.

And all this will occure while configuring the new installed ROM (When you enter an email for Google Play, and set Timezone etc.).

And the password can be stored so it can't be stolen by hacker ?

Is this possible please ? If yes, can you purpose me a path to follow in order to achieve this ? Of course I don't ask to make it etc. Just to give me a similar things already done in the past by someone else etc.

Big thanks in advance for your help !

**Comment by ypid** [comment]
> 10 PIN will be given for him and be written into a paper so if someday he forgot the password, he can recover it by using this PINs just like Google do it for Gmail.

This sounds more like the requirements of a company for their employee phones to me and would better be implemented outside of the OS using https://developers.google.com/android/work/overview.

Also, I don’t think such a feature is wanted for this project. The owner will have to take care of their password. No third party shall have "recovery keys". I am not aware of recovery keys being a thing for Android devices.

Closing as not fitting to the project.
