### ISSUE TITLE
Where is the backup patch?

### ISSUE THREAD

**Issue by Atemu** [hashbang/os#46]
Hi, in the README it states that you include "Minor OS changes made to allow backing up any app" for Seedvault but I wasn't able to find the patch(es) for it. Could you give me a pointer?

**Comment by ypid** [comment]
I reintroduced it in an not yet merged PR. See https://github.com/ypid/os/blob/machine-abstraction/config/patches/platform/ignore-allowbackup-false.patch. This PR has not yet been updated to Android 11. Ref: #40
